name: Build and Push Upload API

on:
  push:
    branches:
      - main
    paths:
      - "apps/upload-api/**"

permissions:
  id-token: write
  contents: read

# env:
#   ECR_REPOSITORY: ahmad/eks-gpu-inference-platform

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: configure aws credentials
      #   uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
      #   with:
      #     role-to-assume: arn:aws:iam::680688655542:role/Github_Actions_OIDC_role
      #     role-session-name: samplerolesession
      #     aws-region: us-east-1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::680688655542:role/Github_Actions_OIDC_role # Change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get short Git SHA
        id: tag
        run: echo "tag=upload-api-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/upload-api
          push: true
          tags: |
            ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.tag.outputs.tag }}